### ISSUE TITLE
Not able to run Opensearch runner version 2.5.0.0 or 2.9.0.0

### ISSUE THREAD

**Issue by mx-foxtel** [codelibs/opensearch-runner#2]
Java version: 17

```java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    org/opensearch/analysis/common/CommonAnalysisPlugin.lambda$getPreConfiguredTokenFilters$15(Lorg/apache/lucene/analysis/TokenStream;)Lorg/apache/lucene/analysis/TokenStream; @12: invokespecial
  Reason:
    Type 'org/tartarus/snowball/ext/FrenchStemmer' (current frame, stack[3]) is not assignable to 'org/tartarus/snowball/SnowballStemmer'
  Current Frame:
    bci: @12
    flags: { }
    locals: { 'org/apache/lucene/analysis/TokenStream' }
    stack: { uninitialized 0, uninitialized 0, 'org/apache/lucene/analysis/TokenStream', 'org/tartarus/snowball/ext/FrenchStemmer' }
  Bytecode:
    0000000: bb02 8859 2abb 02c0 59b7 02c2 b702 c3b0
    0000010:                                        


	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at org.codelibs.opensearch.runner.OpenSearchRunner.build(OpenSearchRunner.java:351)
	at org.codelibs.opensearch.runner.OpenSearchRunner.build(OpenSearchRunner.java:310)
```

**Comment by marevol** [comment]
Did you use a proper Lucene version?
